name: 'compress-action'
description: 'Brotli compress all .js .html and .css files in a directory recursively'
inputs:
  target-directory:
    description: 'directory to target'
    required: true
    default: '.'
  docker_registry_url:
    description: 'Docker registry URL'
    required: true
  docker_registry_username:
    description: 'Docker registry username'
    required: true
  docker_registry_password:
    description: 'Docker registry password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker_registry_url }}
        username: ${{ inputs.docker_registry_username }}
        password: ${{ inputs.docker_registry_password }}

    - name: compress
      shell: bash
      run: |
        docker build -t compress-action-image .
        docker run --rm -v ${{ github.workspace }}:${{ github.workspace }} compress-action-image ${{ inputs.target-directory }}
